# Generated by Django 4.2.16 on 2025-02-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='number',
            new_name='Amount',
        ),
    ]
